{"uuid": "47e5b4fd-a429-41ee-97bb-0bf022f09e62", "children": ["f2f31bfd-ef34-4720-9114-b109cab89e1e"], "befores": [{"name": "setup_browser", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: <html>\r\n<head><title>401 Authorization Required</title></head>\r\n<body bgcolor=\"white\">\r\n<center><h1>401 Authorization Required</h1></center>\r\n<hr><center>nginx/1.14.2</center>\r\n</body>\r\n</html>\r\n\n\n", "trace": "  File \"/Users/user/qa_guru/qa_guru_5_12/venv/lib/python3.9/site-packages/pluggy/_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"/Users/user/qa_guru/qa_guru_5_12/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 1111, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"/Users/user/qa_guru/qa_guru_5_12/venv/lib/python3.9/site-packages/_pytest/fixtures.py\", line 883, in call_fixture_func\n    fixture_result = next(generator)\n  File \"/Users/user/qa_guru/qa_guru_5_12/conftest.py\", line 44, in setup_browser\n    driver = webdriver.Remote(\n  File \"/Users/user/qa_guru/qa_guru_5_12/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 275, in __init__\n    self.start_session(capabilities, browser_profile)\n  File \"/Users/user/qa_guru/qa_guru_5_12/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 365, in start_session\n    response = self.execute(Command.NEW_SESSION, parameters)\n  File \"/Users/user/qa_guru/qa_guru_5_12/venv/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py\", line 430, in execute\n    self.error_handler.check_response(response)\n  File \"/Users/user/qa_guru/qa_guru_5_12/venv/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py\", line 211, in check_response\n    raise exception_class(value)\n"}, "start": 1685049054573, "stop": 1685049054855}], "start": 1685049054573, "stop": 1685049055021}